apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapnil-deployment
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: gagan-app
        image: gagandeepthinknyx/intel-app:v4
        ports:
        - containerPort: 80
