name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: kube-deploy
        run: kubectl apply -f deploy.yaml
      - name: list deployments
        run: kubectl get deployments
      - name: list services
        run: kubectl get services
