name: mypipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "Build running"
          sleep 5
      - name: second step or task
        run: |
          echo "Build completed"
          sleep 10
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run a one-line script
        run: |
          echo "Test running"
          sleep 10
      - name: second step or task
        run: |
          echo "Test completed"
          sleep 10 
  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run a one-line script
        run: |
          echo "deploy running"
          sleep 10
